name: Get Arxiv Papers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests markdown pdfplumber re langchain time openai arxiv tadm

      - name: run script
        run: |
          git pull
          python get_arxiv_paper_release.py

      - name: push markdown file
        run: |
          git config user.name hongge831
          git config user.email hongge831@163.com
          git add .
          git commit -m "update"
          git push --force origin main
